### ISSUE TITLE
Schema does not load from local

### ISSUE THREAD

**Issue by escauley** [HadleyKing/bco-tool#10]
When supplying a local copy of the schema https://github.com/FDA-ARGOS/data.argosdb/blob/v0.3_Jan/schema/extensionDomainV1

![image](https://user-images.githubusercontent.com/16712699/150598429-28737db3-097c-4bbb-9616-4529395d0eb3.png)

The same issues arise when using a local copy of the default schema

'options.schema' contains a path name or URL as a string. 'options.schema.name' is called, but since 'options.schema' is a string there cannot be an attribute 'name'. 'options.schema' needs to be a dictionary to call attribute 'name'

I can't designate assignees so tagging you here @acoleman2000

**Comment by HadleyKing** [comment]
986e459093147bdd4575d45446ff5967145d83fd
