### ISSUE TITLE
BCO with extension domain does not convert correctly

### ISSUE THREAD

**Issue by escauley** [HadleyKing/bco-tool#11]
For BCO https://data.glygen.org/GLY_000024/v-1.9.9/bco

![image](https://user-images.githubusercontent.com/16712699/150602484-f484cc40-24d6-4377-9055-788af01c0c04.png)

A converted BCO is still generated that contains changes based on the default schema used. The extension domain is deleted, but in the original BCO there was information that needs to be carried over.

The extension domain is listed in the default schema:

![image](https://user-images.githubusercontent.com/16712699/150605101-50c6c90d-1682-47a4-bac7-47a85c3e6111.png)

An extension domain schema was also provided by the BCO team: https://raw.githubusercontent.com/FDA-ARGOS/data.argosdb/v0.3_Jan/schema/extensionDomainV1

Original BCO extension domain (from https://opensource.ieee.org/2791-object/ieee-2791-schema/-/raw/master/2791object.json):

![image](https://user-images.githubusercontent.com/16712699/150602859-f2ef2d11-d5ad-4cab-9051-422098cb1504.png)

'Converted' BCO contains no extension domain, it appears to be deleted in the conversion process

I can't designate assignee so tagging you here @acoleman2000

**Comment by HadleyKing** [comment]
986e459093147bdd4575d45446ff5967145d83fd
